sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
language: node_js
node_js:
  - '14.15.1'
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
